### PR TITLE
Use String() instead of toString() on message parameter in handleTrace

### PR DESCRIPTION
**Pull request by ebrenes**
The handleTrace method was throwing an exception when the message parameter was null/undefined since those primitives do not implement a toString method. I've replaced this toString() with String() which handles those edge cases while retaining the behavior of toString.

Reference:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#examples

### CODE REVIEW

**Comment by willmorgan** [comment]
@ebrenes I've fixed the Semaphore build problem, looks like it's failing on Node 6.x though.

**Comment by ebrenes** [comment]
@willmorgan , I'm having issues getting Node 6.x to run the tests successfully on any of my systems. I've tried on macOs, Windows, Linux Ubuntu checking out from develop (without my changes) and I get the same 4 errors. I've also asked a co-worker to clone the repo and try themselves, to try and rule out any user error on my part. 

I know that the build runs correctly on semaphore for develop (https://semaphoreci.com/willmorgan/winston-azure-application-insights/branches/develop/builds/10), but I just cannot get the test to behave similarly locally. 

I'm doing the following: 
1.  Clone from Github into a clean directory
2. run `nvm use 6.17.1`
3. run `npm install`
4. run `npm run test`

I can get the tests to pass if I don't clear node_modules in between checking builds from node 8 to node 6, for example. In the semaphore logs I don't see any report from the npm install for Node 6, like I see when I run `bash ci/test.sh` locally.

If I do something like:
1. Clone from Github into a clean directory
2. run `nvm use 8.17.0`
3. run `npm install`
4. run `nvm use 6.17.1`
5. run `npm run test`

Everything passes with flying colors. Is the `node_modules` being cleared between the different build pipelines?

**Comment by willmorgan** [comment]
There is an easier fix - version bump to 3.x and drop support for Node 6 😉

**Comment by ebrenes** [comment]
> There is an easier fix - version bump to 3.x and drop support for Node 6 😉

I've made some changes to the PR to reflect this. I also did an `npm audit fix` and bumped mocha to v7 which is the most recent version still supporting Node 8.x, let me know if you're okay with the changes.

**Comment by willmorgan** [comment]
@dhensby - any more breaking changes for you?

**Review by dhensby — APPROVED** [review]

**Comment by dhensby** [comment]
shouldn't this PR be against https://github.com/bragma/winston-azure-application-insights instead of this repo?

**Comment by willmorgan** [comment]
No, that repo has been abandoned.

**Comment by ebrenes** [comment]
@willmorgan is there anything else I need to do on my part?

**Comment by willmorgan** [comment]
@ebrenes If you can mark this version as 3.0.0 (we'll skip alpha) then we're good to go. I can get the release done later.

**Comment by ebrenes** [comment]
@willmorgan done!

**Comment by willmorgan** [comment]
@ebrenes Thanks for this, 3.0.0 tag should now be available on releases + npm 🎉

**Pull request merged**
